# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-29 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StepModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='step',
            new_name='recipe',
        ),
    ]
