# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-29 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StepModel', '0002_auto_20190829_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipestep', to='RecipeModel.Recipe'),
        ),
    ]
