# Generated by Django 2.2.4 on 2019-08-31 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StepModel', '0003_auto_20190829_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ('step_txt',)},
        ),
        migrations.RenameField(
            model_name='step',
            old_name='name',
            new_name='step_txt',
        ),
    ]
