# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-29 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeModel', '0002_auto_20190829_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermodel', to='userModel.UserModel', unique=True),
        ),
    ]
