# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-29 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IngredientModel', '0001_initial'),
        ('RecipeModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='RecipeModel.Recipe'),
        ),
    ]
