# Generated by Django 2.2.4 on 2019-08-31 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IngredientModel', '0003_auto_20190829_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='available',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='stock',
        ),
    ]
