# Generated by Django 2.2.4 on 2019-08-31 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IngredientModel', '0004_auto_20190831_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('text',)},
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='text',
        ),
    ]
